---
- name: mkdir jobs directory
  file:
    path="{{JENKINS_JOBS_DIR}}/{{item}}"
    state=directory
    owner=jenkins
    group=jenkins
    mode=755
  with_items: JENKINS_JOB_NAMES

- name: set jobs config file
  copy:
    src=jobs/{{item}}/config.xml
    dest={{ jenkins_jobs_dir }}/{{item}}/config.xml
    owner=jenkins
    group=jenkins
    mode=644
  with_items: JENKINS_JOB_NAMES
  notify: restart jenkins

- name: mkdir jobs workspace
  file:
    path="{{JENKINS_JOBS_DIR}}/{{item}}/workspace"
    state=directory
    owner=jenkins
    group=jenkins
    mode=755
  with_items: JENKINS_JOB_NAMES
