---
- name: install yum packages
  yum: name={{ item }} state=installed
  with_items:
    - zlib-devel
    - bzip2-devel
    - openssl-devel
    - ncurses-devel
    - sqlite-devel
    - readline-devel
    - tk-devel

- name: download install src
  get_url: url=https://www.python.org/ftp/python/2.7.11/Python-2.7.11.tgz dest={{ tmp_dir }}

- name: unarchive src file
  unarchive: src={{ tmp_dir }}/Python-2.7.11.tgz dest={{ tmp_dir }} copy=no

- name: configure python src
  command: chdir={{ tmp_dir }}/Python-2.7.11 ./configure --prefix=/usr/local/python2.7 creates=/usr/local/python2.7/bin/python2.7

- name: make python src
  command: chdir={{ tmp_dir }}/Python-2.7.11 make creates=/usr/local/python2.7/bin/python2.7

- name: install python src
  command: chdir={{ tmp_dir }}/Python-2.7.11 make install creates=/usr/local/python2.7/bin/python2.7

- name: export path
  lineinfile: dest=/root/.bash_profile line='export PATH=/usr/local/python2.7/bin:$PATH'

- name: wget get-pip.py
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest={{ tmp_dir }}

- name: install pip-7.1.2 setuptools-18.7.1 wheel-0.26.0
  command: /usr/local/python2.7/bin/python2.7 {{tmp_dir}}/get-pip.py creates=/usr/local/python2.7/lib/python2.7/site-packages/pip

