---
- name: get install pip script
  get_url:
    url=https://bootstrap.pypa.io/get-pip.py
    dest=/tmp/
    mode=0755

- name: run install script
  shell:
    python /tmp/get-pip.py
    creates=/usr/bin/aws

- name: install aws cli
  pip:
    name=awscli
    executable=/usr/bin/pip
    state=latest
