---
- name: install yum packages
  yum: name={{ item }} state=installed
  with_items:
    - ruby
    - ruby-devel

- name: install terraforming
  gem: name=terraforming

- name: set enviroments
  lineinfile:
    dest={{USER_HOME}}/.bash_profile
    line={{item}}
  with_items:
    - 'export AWS_ACCESS_KEY_ID={{AWS_ACCESS_KEY_ID}}'
    - 'export AWS_SECRET_ACCESS_KEY={{AWS_SECRET_ACCESS_KEY}}'
    - 'export AWS_DEFAULT_REGION={{AWS_DEFAULT_REGION}}'

