---
- hosts: localhost
  sudo: yes
  roles:
    - common
#    - serverspec
#    - bundler
#    - docker
#    - jenkins
#    - zookeeper3.4
#    - python2.7
#    - cassandra2.2
#    - maven3.3.9
#    - ruby
#    - memcached1.4
#    - mysql5.6
#  tasks:
#    - name: bundle install for provisioner
#      command: chdir={{ provisioner_home }} {{ ruby_home }}/bin/bundle
