---
- name: install yum packages
  yum: name={{ item }} state=installed
  with_items:
    - java-1.7.0-openjdk
    - java-1.7.0-openjdk-devel

- name: download install src
  get_url: url=http://archive.apache.org/dist/maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.tar.gz dest={{ tmp_dir }}/apache-maven-3.1.1-bin.tar.gz

- name: unarchive src file
  unarchive: src={{ tmp_dir }}/apache-maven-3.1.1-bin.tar.gz dest={{ tmp_dir }} copy=no

- name: copy dir
  copy: src={{ tmp_dir }}/apache-maven-3.1.1/ dest=/usr/local/maven3.1.1/

- name: chmod
  file: path=/usr/local/maven3.1.1/bin/mvn mode=755

- name: export path
  lineinfile: dest=/root/.bash_profile line='export PATH=/usr/local/maven3.1.1/bin:$PATH'

