---
- name: install yum packages
  yum: name={{ item }} state=installed
  with_items:
    - libevent
    - libevent-devel
#    - perl-Test-Harness-3.17-141.el6_7.1

#- name: download install src
#  get_url: url=https://github.com/libevent/libevent/archive/release-1.4.15-stable.tar.gz dest={{ tmp_dir }}

- name: download install src
  get_url: url=http://memcached.org/files/memcached-1.4.25.tar.gz dest={{ tmp_dir }}

- name: unarchive src file
  unarchive: src={{ tmp_dir }}/memcached-1.4.25.tar.gz dest={{ tmp_dir }} copy=no

- name: configure src
  command: chdir={{ tmp_dir }}/memcached-1.4.25 ./configure --prefix=/usr/local/memcached-1.4.25 creates=/usr/local/memcached-1.4.25

- name: make src
  command: chdir={{ tmp_dir }}/memcached-1.4.25 make creates=/usr/local/memcached-1.4.25

#- name: make test
#  command: chdir={{ tmp_dir }}/memcached-1.4.25 make test creates=/usr/local/memcached-1.4.25

- name: make install src
  command: chdir={{ tmp_dir }}/memcached-1.4.25 make install creates=/usr/local/memcached-1.4.25

- name: add memcached group
  group: name=memcached

- name: add memcached user
  user: name=memcached group=memcached

- name: export path
  lineinfile: dest=/home/memcached/.bash_profile line='export PATH=/usr/local/memcached-1.4.25/bin:$PATH'

- name: set service script
  copy: src=memcached dest=/etc/init.d/memcached mode=0755

#- name: set script
#  copy: src=scripts dest=/usr/local/memcached-1.4.25

- name: mkdir run directory
  file: path=/usr/local/memcached-1.4.25/var/run state=directory recurse=yes owner=memcached group=memcached mode=755

- name: mkdir lock directory
  file: path=/usr/local/memcached-1.4.25/var/lock state=directory recurse=yes owner=memcached group=memcached mode=755

- name: mkdir conf directory
  file: path=/usr/local/memcached-1.4.25/conf state=directory recurse=yes owner=memcached group=memcached mode=755

- name: set conf
  copy: src=memcached.conf dest=/usr/local/memcached-1.4.25/conf/memcached
