---
- name: install dependency package
  yum:
    name={{item}}
    state=installed
  with_items:
    - wget
    - gcc-c++
    - pcre-devel
    - zlib-devel
    - make
    - unzip
    - openssl-devel
    - perl-devel
    - perl-ExtUtils-Embed
    - gd-devel

- name: download ngx_pagespeed
  get_url:
    url=https://github.com/apache/incubator-pagespeed-ngx/archive/v{{ NPS_VERSION }}.zip
    dest=/tmp/v{{ NPS_VERSION }}.zip
    mode=0755

- name: unarchive ngx_pagespeed
  unarchive:
    src=/tmp/v{{ NPS_VERSION }}.zip
    dest=/tmp
    remote_src=yes
    mode=0755

- name: set psol_url
  shell: scripts/format_binary_url.sh PSOL_BINARY_URL
  args:
    chdir: /tmp/incubator-pagespeed-ngx-{{ NPS_VERSION }}
  register: psol_url
  changed_when: False

# - name: download psol
#   get_url:
#     url=https://dl.google.com/dl/page-speed/psol/{{NPS_VERSION}}.tar.gz
#     dest=/tmp/ngx_pagespeed-release-{{NPS_VERSION}}-beta/{{NPS_VERSION}}.tar.gz
#     mode=0755

- name: unarchive psol
  unarchive:
    src={{ psol_url.stdout }}
    dest=/tmp/incubator-pagespeed-ngx-{{ NPS_VERSION }}
    remote_src=yes
    mode=0755

- name: download nginx
  get_url:
    url=http://nginx.org/download/nginx-{{ NGINX_VERSION }}.tar.gz
    dest=/tmp/nginx-{{ NGINX_VERSION }}.tar.gz
    mode=0755

- name: unarchive nginx
  unarchive:
    src=/tmp/nginx-{{ NGINX_VERSION }}.tar.gz
    dest=/tmp
    remote_src=yes
    mode=0755

- name: configure
  shell:
    chdir=/tmp/nginx-{{NGINX_VERSION}}
    creates=/usr/sbin/nginx
    ./configure
    --prefix=/etc/nginx
    --sbin-path=/usr/sbin/nginx
    --conf-path=/etc/nginx/nginx.conf
    --http-client-body-temp-path=/var/lib/nginx/tmp/client_body
    --http-proxy-temp-path=/var/lib/nginx/tmp/proxy
    --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi
    --pid-path=/var/run/nginx.pid
    --lock-path=/var/run/nginx.lock
    --error-log-path=/var/log/nginx/error.log
    --http-log-path=/var/log/nginx/access.log
    --add-module=/tmp/incubator-pagespeed-ngx-{{ NPS_VERSION }}
    --with-http_gzip_static_module
    --with-http_stub_status_module
    --with-http_ssl_module
    --with-pcre
    --with-file-aio
    --with-http_realip_module
    --with-http_perl_module
    --with-http_image_filter_module
    --without-http_scgi_module
    --without-http_uwsgi_module

- name: make
  shell:
    chdir=/tmp/nginx-{{NGINX_VERSION}}
    creates=/usr/sbin/nginx
    make

- name: make install
  shell:
    chdir=/tmp/nginx-{{NGINX_VERSION}}
    creates=/usr/sbin/nginx
    make install

- name: create link
  file:
    src=/usr/sbin/nginx
    dest=/bin/nginx
    state=link

- name: service file
  copy:
    src=nginx.service
    dest=/usr/lib/systemd/system/nginx.service
    mode=0644
  notify: systemctl daemon-reload

- name: service enable
  service:
    name=nginx
    enabled=yes

- name: create nginx group
  group:
    name=nginx
    gid=911

- name: create nginx user
  user:
    name=nginx
    group=nginx
    uid=995
    createhome=no
    home=/var/lib/nginx
    shell=/sbin/nologin
    system=yes
    comment="Nginx web server"

- name: setting logrotate
  copy:
    src=logrotate.nginx
    dest=/etc/logrotate.d/nginx
    mode=0644

- name: create directory
  file:
    path={{item}}
    state=directory
    recurse=yes
    mode=0700
    owner=nginx
    group=nginx
  with_items:
    - /var/lib/nginx/tmp/client_body
    - /var/lib/nginx/tmp/proxy

- name: create directory
  file:
    path={{item}}
    state=directory
    recurse=yes
  with_items:
    - /usr/share/nginx
