---
- name: install yum packages
  yum: name={{ item }} state=installed
  with_items:
    - java-1.7.0-openjdk
    - java-1.7.0-openjdk-devel

- name: download install src
  get_url: url=http://ftp.riken.jp/net/apache/cassandra/2.2.4/apache-cassandra-2.2.4-bin.tar.gz dest={{ tmp_dir }}/

- name: unarchive src file
  unarchive: src={{ tmp_dir }}/apache-cassandra-2.2.4-bin.tar.gz dest={{ tmp_dir }}/ copy=no

#- name: copy dir
#  copy: src=/usr/local/apache-cassandra-2.2.4/ dest={{cassandra_home}}/

- name: copy dir
  command: cp -r {{ tmp_dir }}/apache-cassandra-2.2.4 {{cassandra_home}} creates={{cassandra_home}}

- name: set conf
  template: src=cassandra.yaml dest={{cassandra_home}}/conf/cassandra.yaml

#- name: make link
#  file: src=/usr/local/apache-cassandra-2.2.4 dest={{cassandra_home}} state=link

- name: export path
  lineinfile: dest=/root/.bash_profile line='export PATH={{cassandra_home}}/bin:$PATH'

- name: set env
  lineinfile: dest=/root/.bash_profile line='export CQLSH_HOST={{cassandra_host}}'

- name: check running cassandra
  shell: ps aux | grep [C]assandraDaemon | wc -l
  register: cassandra_process
  changed_when: false
  always_run: yes

#- debug: var=cassandra_process

- name: run cassandra
  command: /usr/local/cassandra/bin/cassandra
  when: cassandra_process.stdout == "0"
  async: 15
  poll: 0

- name: wait for run cassandra
  wait_for: host={{cassandra_host}} port=9042 delay=10 state=started timeout=300
  when: cassandra_process.stdout == "0"

