---
- name: download install script
  get_url:
    url=https://git.io/nodebrew
    dest=/tmp/nodebrew

- name: run install script
  shell:
    perl /tmp/nodebrew setup
    creates={{ansible_user_dir}}.nodebrew

- name: set enviroment
  lineinfile:
    dest={{ansible_user_dir}}/.bash_profile
    line='export PATH=$HOME/.nodebrew/current/bin:$PATH'

