---
- name: download jq binary
  get_url:
    url=https://github.com/stedolan/jq/releases/download/jq-{{JQ_VERSION}}/jq-linux64
    dest=/usr/local/bin/jq-{{JQ_VERSION}}
    mode=0755

- name: create symlink
  file:
    src=/usr/local/bin/jq-{{JQ_VERSION}}
    dest=/usr/local/bin/jq
    state=link

